---
name: Inventory
description: Our company inventory includes employees and equipment
version: 2022-09-09
game:
  route: /hello
  templatePath: ./__game_template.html
  backends:
  - http://service-a
  - http://service-b
  - http://service-c
  - http://service-d
endpoints:
- path: /machines
  kind: basic
  method: GET
  code: 200
  response: "We have plenty of machines in our factory as you can see as follows..."
- path: /machines/add
  kind: basic
  method: POST
  code: 200
  response: "New machine has been added"
- path: /buildings
  kind: basic
  method: GET
  code: 200
  response: "We have production and office buildings in many cities"
- path: /customers
  kind: basic
  method: GET
  code: 200
  response: "Our customers are listed there:"
- path: /publications
  dsn: "postgres://develdb:__PASSWORD__@pgsql-1:5432/develdb"
  kind: psql
  method: GET
  query: "select id, database as db, results as r from publications;"
  response: |
    {
      "message": "nazdarek",
      "results": {{ json . }}
    }
    
    
